In [ ]:

# 1 dimension array
import numpy as np
a=[1,2,3,4,5]
x= np.array(a)
print(x)

[1 2 3 4 5]


**diamension of array** in [above and below]

In [ ]:
x.ndim #no.of dimensionss


1

In [ ]:
# 2 dimension array
a=[1,2,3,4]
b=[10,20,30,40]
y=np.array([a,b])
print(y)

[[ 1  2  3  4]
 [10 20 30 40]]


In [ ]:
y.ndim

2

**Reshaping numpy array**


In [ ]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
# Reshape array
a=([1,2,3,4,])
np.reshape(a,(2,2))

array([[1, 2],
       [3, 4]])

In [ ]:
x=np.arange(1,16)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
x.size #no.of element in array

15

In [ ]:
x.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

**Array of your choice**

In [ ]:
np.full((3,3),10)# np.full is constant value


array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [ ]:
np.ones((3,3))*10

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

**Identity matrix**

In [ ]:
#np.eye --create identity matrix
x = np.eye(5, k = -1)# 5 is n.of row ,k=-1 is diagonal
print(x)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


**Evenly spaced ndarray**

In [ ]:
np.arange(5,11)# range of integer

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(0,11,2)# add 2

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
np.linspace(0,1,5)# 0 is start,1 is end,5 is range

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

29.end−start / n−1

**Transpose of a NumPy array**

In [ ]:
x = np.arange(1,16).reshape(5,3)
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [ ]:
x.transpose()

array([[ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14],
       [ 3,  6,  9, 12, 15]])

**Indexing and Slicing of NumPy Array**

**1D NumPy arrays**

In [ ]:
a = np.arange(1,10)
print(a)


[1 2 3 4 5 6 7 8 9]


In [ ]:
x = np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
x[1:3,1:3]

array([[5, 6],
       [8, 9]])

Stacking and Concatenating NumPy Arrays

In [5]:
import numpy as np
a = np.arange(1,6)
b = np.arange(6,11)
print(a)
print(b)


[1 2 3 4 5]
[ 6  7  8  9 10]
