Concatenating

In [4]:
import numpy as np
a = np.arange(1,10).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [5]:
np.concatenate((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [6]:
np.concatenate((a,b), axis = 1)

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

Broadcasting in NumPy arrays

In [7]:
a = np.arange(10,21,2)
b = np.array([[2],[2]])

In [8]:
print(a)

[10 12 14 16 18 20]


In [9]:
print(b)

[[2]
 [2]]


In [10]:
z = a+b
print(z)

[[12 14 16 18 20 22]
 [12 14 16 18 20 22]]


In [11]:
a = np.arange(10,21,2)
a+2

array([12, 14, 16, 18, 20, 22])

In [12]:
a-b

array([[ 8, 10, 12, 14, 16, 18],
       [ 8, 10, 12, 14, 16, 18]])

In [13]:
a*b

array([[20, 24, 28, 32, 36, 40],
       [20, 24, 28, 32, 36, 40]])

In [14]:
a/b

array([[ 5.,  6.,  7.,  8.,  9., 10.],
       [ 5.,  6.,  7.,  8.,  9., 10.]])

In [15]:
a = np.ones((3,3))
b = np.array([2])
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [16]:
print(b)

[2]


In [17]:
a+b

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [18]:
a-b

array([[-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.]])